### ISSUE TITLE
Cs50 pset 7 movies check exploit

### ISSUE THREAD

**Issue by VoxSkynned11** [cs50/problems#128]
In the 13.sql query, the check passes if you put a line like "AND people.name != "Kevin Bacon".
Kevin bacon should not appear in the query that lists everyone that starred in a movie with kevin bacon(1958) but if there was someone else with the same name they wouldn't be included

**Comment by CarterZenke** [comment]
Thanks again for raising this one, @VoxSkynned11! We'll leave the check as-is, since we'd need to generate artificial data for this to be a correctness issue: for example, the database would need to include a movie in which a separate Kevin Bacon stars in a movie with the real Kevin Bacon (which to our knowledge hasn't happened yet!). This is nevertheless a good idea for thinking about good design of SQL queries!
