### ISSUE TITLE
It is impossible to check

### ISSUE THREAD

**Issue by Goldenpes** [cs50/problems#152]
The following error code appears after trying to execute check50 function for hello.c,

"Make sure your username and/or personal access token are valid and check50 is enabled for your account. To enable check50, please go to https://submit.cs50.io/ in your web browser and try again. For instructions on how to set up a personal access token, please visit https://cs50.ly/github "

I have Personal Access Tokens via GitHub.
Thank's for help
![2022-10-11_20-13-22](https://user-images.githubusercontent.com/115190497/195157731-15e68d53-930c-4040-95ea-88f9290fb036.png)

**Comment by rongxin-liu** [comment]
Please make sure your access token indeed has the `repo` scope turned on and you have copy-pasted your access token to the terminal correctly. You could also try configuring SSH for your Codespace instead of using access token:
https://cs50.harvard.edu/x/2022/new/#configure-git-to-use-ssh-in-your-cs50-codespace
